-- Clear existing data first
DELETE FROM public.votes;
DELETE FROM public.candidates;
DELETE FROM public.partylists;

-- Insert candidates for all 10 departments with standard positions
-- Each position has 3-4 Filipino-named candidates

-- CCS Candidates
INSERT INTO public.candidates (department, position, candidate_name) VALUES
-- President
('CCS', 'President', 'Maria Santos'),
('CCS', 'President', 'Juan Reyes'),
('CCS', 'President', 'Sofia Cruz'),
('CCS', 'President', 'Miguel Torres'),
-- Vice President
('CCS', 'Vice President', 'Ana Garcia'),
('CCS', 'Vice President', 'Carlos Mendoza'),
('CCS', 'Vice President', 'Isabel Ramos'),
-- Secretary
('CCS', 'Secretary', 'Rosa Fernandez'),
('CCS', 'Secretary', 'Diego Lopez'),
('CCS', 'Secretary', 'Carmen Gonzales'),
('CCS', 'Secretary', 'Rafael Diaz'),
-- Treasurer
('CCS', 'Treasurer', 'Luisa Martinez'),
('CCS', 'Treasurer', 'Antonio Sanchez'),
('CCS', 'Treasurer', 'Elena Rivera'),
-- Auditor
('CCS', 'Auditor', 'Pedro Morales'),
('CCS', 'Auditor', 'Beatriz Castro'),
('CCS', 'Auditor', 'Francisco Ortiz'),
('CCS', 'Auditor', 'Teresa Navarro'),
-- PIO
('CCS', 'PIO', 'Jose Herrera'),
('CCS', 'PIO', 'Gabriela Flores'),
('CCS', 'PIO', 'Manuel Silva'),
-- Business Manager
('CCS', 'Business Manager', 'Patricia Jimenez'),
('CCS', 'Business Manager', 'Roberto Vargas'),
('CCS', 'Business Manager', 'Claudia Ruiz'),
('CCS', 'Business Manager', 'Alejandro Romero'),
-- Representative
('CCS', 'Representative', 'Victoria Alvarez'),
('CCS', 'Representative', 'Fernando Perez'),
('CCS', 'Representative', 'Daniela Aguilar'),
-- Senator
('CCS', 'Senator', 'Lorenzo Medina'),
('CCS', 'Senator', 'Mariana Gutierrez'),
('CCS', 'Senator', 'Ricardo Castillo'),
('CCS', 'Senator', 'Angela Delgado'),
-- Governor
('CCS', 'Governor', 'Ernesto Vega'),
('CCS', 'Governor', 'Natalia Ramirez'),
('CCS', 'Governor', 'Alberto Moreno');

-- BS Nursing Candidates
INSERT INTO public.candidates (department, position, candidate_name) VALUES
('BS Nursing', 'President', 'Kristine Tan'),
('BS Nursing', 'President', 'Marco Lim'),
('BS Nursing', 'President', 'Angela Dy'),
('BS Nursing', 'Vice President', 'Jasmine Ong'),
('BS Nursing', 'Vice President', 'Patrick Go'),
('BS Nursing', 'Vice President', 'Michelle Chua'),
('BS Nursing', 'Secretary', 'Rachel Lee'),
('BS Nursing', 'Secretary', 'Vincent Sy'),
('BS Nursing', 'Secretary', 'Sarah Kho'),
('BS Nursing', 'Secretary', 'Daniel Ng'),
('BS Nursing', 'Treasurer', 'Jennifer Tan'),
('BS Nursing', 'Treasurer', 'Richard Uy'),
('BS Nursing', 'Treasurer', 'Catherine Lao'),
('BS Nursing', 'Auditor', 'Andrew Tiu'),
('BS Nursing', 'Auditor', 'Stephanie Co'),
('BS Nursing', 'Auditor', 'Benjamin Ang'),
('BS Nursing', 'Auditor', 'Nicole Yap'),
('BS Nursing', 'PIO', 'Christopher Tan'),
('BS Nursing', 'PIO', 'Diana Wong'),
('BS Nursing', 'PIO', 'Jonathan Lim'),
('BS Nursing', 'Business Manager', 'Melissa Chan'),
('BS Nursing', 'Business Manager', 'Kenneth Ong'),
('BS Nursing', 'Business Manager', 'Vanessa Goh'),
('BS Nursing', 'Business Manager', 'Raymond Teo'),
('BS Nursing', 'Representative', 'Amanda Chua'),
('BS Nursing', 'Representative', 'Steven Dy'),
('BS Nursing', 'Representative', 'Sophia Lim'),
('BS Nursing', 'Senator', 'Michael Tan'),
('BS Nursing', 'Senator', 'Kristina Go'),
('BS Nursing', 'Senator', 'Bryan Lee'),
('BS Nursing', 'Senator', 'Isabel Ng'),
('BS Nursing', 'Governor', 'Philip Uy'),
('BS Nursing', 'Governor', 'Cassandra Kho'),
('BS Nursing', 'Governor', 'Edward Sy');

-- College of Psychology Candidates
INSERT INTO public.candidates (department, position, candidate_name) VALUES
('College of Psychology', 'President', 'Bianca Reyes'),
('College of Psychology', 'President', 'Nathan Cruz'),
('College of Psychology', 'President', 'Samantha Torres'),
('College of Psychology', 'Vice President', 'Joshua Santos'),
('College of Psychology', 'Vice President', 'Tricia Garcia'),
('College of Psychology', 'Vice President', 'Christian Ramos'),
('College of Psychology', 'Secretary', 'Kimberly Fernandez'),
('College of Psychology', 'Secretary', 'Lawrence Lopez'),
('College of Psychology', 'Secretary', 'Erica Gonzales'),
('College of Psychology', 'Secretary', 'Jerome Diaz'),
('College of Psychology', 'Treasurer', 'Angelica Martinez'),
('College of Psychology', 'Treasurer', 'Dennis Sanchez'),
('College of Psychology', 'Treasurer', 'Monica Rivera'),
('College of Psychology', 'Auditor', 'Gerald Morales'),
('College of Psychology', 'Auditor', 'Cynthia Castro'),
('College of Psychology', 'Auditor', 'Arnold Ortiz'),
('College of Psychology', 'Auditor', 'Josephine Navarro'),
('College of Psychology', 'PIO', 'Ryan Herrera'),
('College of Psychology', 'PIO', 'Christine Flores'),
('College of Psychology', 'PIO', 'Kevin Silva'),
('College of Psychology', 'Business Manager', 'Sandra Jimenez'),
('College of Psychology', 'Business Manager', 'Harold Vargas'),
('College of Psychology', 'Business Manager', 'Vivian Ruiz'),
('College of Psychology', 'Business Manager', 'Jeffrey Romero'),
('College of Psychology', 'Representative', 'Veronica Alvarez'),
('College of Psychology', 'Representative', 'Edwin Perez'),
('College of Psychology', 'Representative', 'Tiffany Aguilar'),
('College of Psychology', 'Senator', 'Gregory Medina'),
('College of Psychology', 'Senator', 'Rachelle Gutierrez'),
('College of Psychology', 'Senator', 'Walter Castillo'),
('College of Psychology', 'Senator', 'Valerie Delgado'),
('College of Psychology', 'Governor', 'Stanley Vega'),
('College of Psychology', 'Governor', 'Pamela Ramirez'),
('College of Psychology', 'Governor', 'Eugene Moreno');

-- College of Engineering Candidates
INSERT INTO public.candidates (department, position, candidate_name) VALUES
('College of Engineering', 'President', 'Paolo Mendoza'),
('College of Engineering', 'President', 'Katrina Reyes'),
('College of Engineering', 'President', 'Marcus Torres'),
('College of Engineering', 'Vice President', 'Joyce Santos'),
('College of Engineering', 'Vice President', 'Emmanuel Cruz'),
('College of Engineering', 'Vice President', 'Andrea Garcia'),
('College of Engineering', 'Secretary', 'Dexter Ramos'),
('College of Engineering', 'Secretary', 'Michelle Fernandez'),
('College of Engineering', 'Secretary', 'Leonard Lopez'),
('College of Engineering', 'Secretary', 'Patricia Gonzales'),
('College of Engineering', 'Treasurer', 'Arthur Diaz'),
('College of Engineering', 'Treasurer', 'Gloria Martinez'),
('College of Engineering', 'Treasurer', 'Winston Sanchez'),
('College of Engineering', 'Auditor', 'Melissa Rivera'),
('College of Engineering', 'Auditor', 'Julius Morales'),
('College of Engineering', 'Auditor', 'Rhoda Castro'),
('College of Engineering', 'Auditor', 'Bernard Ortiz'),
('College of Engineering', 'PIO', 'Marissa Navarro'),
('College of Engineering', 'PIO', 'Gilbert Herrera'),
('College of Engineering', 'PIO', 'Cecilia Flores'),
('College of Engineering', 'Business Manager', 'Norman Silva'),
('College of Engineering', 'Business Manager', 'Virginia Jimenez'),
('College of Engineering', 'Business Manager', 'Alan Vargas'),
('College of Engineering', 'Business Manager', 'Lydia Ruiz'),
('College of Engineering', 'Representative', 'Rodolfo Romero'),
('College of Engineering', 'Representative', 'Evelyn Alvarez'),
('College of Engineering', 'Representative', 'Franklin Perez'),
('College of Engineering', 'Senator', 'Dorothy Aguilar'),
('College of Engineering', 'Senator', 'Martin Medina'),
('College of Engineering', 'Senator', 'Laura Gutierrez'),
('College of Engineering', 'Senator', 'Herman Castillo'),
('College of Engineering', 'Governor', 'Sylvia Delgado'),
('College of Engineering', 'Governor', 'Curtis Vega'),
('College of Engineering', 'Governor', 'Grace Ramirez');

-- CAS Candidates
INSERT INTO public.candidates (department, position, candidate_name) VALUES
('CAS', 'President', 'Adrian Moreno'),
('CAS', 'President', 'Clarissa Reyes'),
('CAS', 'President', 'Miguel Cruz'),
('CAS', 'Vice President', 'Theresa Torres'),
('CAS', 'Vice President', 'Ronaldo Santos'),
('CAS', 'Vice President', 'Carla Garcia'),
('CAS', 'Secretary', 'Howard Ramos'),
('CAS', 'Secretary', 'Lourdes Fernandez'),
('CAS', 'Secretary', 'Oscar Lopez'),
('CAS', 'Secretary', 'Regina Gonzales'),
('CAS', 'Treasurer', 'Barry Diaz'),
('CAS', 'Treasurer', 'Rosario Martinez'),
('CAS', 'Treasurer', 'Calvin Sanchez'),
('CAS', 'Auditor', 'Irene Rivera'),
('CAS', 'Auditor', 'Russell Morales'),
('CAS', 'Auditor', 'Loretta Castro'),
('CAS', 'Auditor', 'Lloyd Ortiz'),
('CAS', 'PIO', 'Norma Navarro'),
('CAS', 'PIO', 'Edgar Herrera'),
('CAS', 'PIO', 'Julia Flores'),
('CAS', 'Business Manager', 'Gary Silva'),
('CAS', 'Business Manager', 'Edna Jimenez'),
('CAS', 'Business Manager', 'Leon Vargas'),
('CAS', 'Business Manager', 'Lillian Ruiz'),
('CAS', 'Representative', 'Perry Romero'),
('CAS', 'Representative', 'Beverly Alvarez'),
('CAS', 'Representative', 'Willis Perez'),
('CAS', 'Senator', 'Bertha Aguilar'),
('CAS', 'Senator', 'Sidney Medina'),
('CAS', 'Senator', 'Mildred Gutierrez'),
('CAS', 'Senator', 'Ross Castillo'),
('CAS', 'Governor', 'Alma Delgado'),
('CAS', 'Governor', 'Clayton Vega'),
('CAS', 'Governor', 'Violet Ramirez');

-- CBA Candidates
INSERT INTO public.candidates (department, position, candidate_name) VALUES
('CBA', 'President', 'Bradford Moreno'),
('CBA', 'President', 'Jeanette Reyes'),
('CBA', 'President', 'Louis Cruz'),
('CBA', 'Vice President', 'Constance Torres'),
('CBA', 'Vice President', 'Wesley Santos'),
('CBA', 'Vice President', 'Pauline Garcia'),
('CBA', 'Secretary', 'Gerard Ramos'),
('CBA', 'Secretary', 'Marjorie Fernandez'),
('CBA', 'Secretary', 'Alvin Lopez'),
('CBA', 'Secretary', 'Priscilla Gonzales'),
('CBA', 'Treasurer', 'Sherman Diaz'),
('CBA', 'Treasurer', 'Geraldine Martinez'),
('CBA', 'Treasurer', 'Clifford Sanchez'),
('CBA', 'Auditor', 'Janice Rivera'),
('CBA', 'Auditor', 'Maurice Morales'),
('CBA', 'Auditor', 'Elaine Castro'),
('CBA', 'Auditor', 'Kent Ortiz'),
('CBA', 'PIO', 'Charlene Navarro'),
('CBA', 'PIO', 'Duane Herrera'),
('CBA', 'PIO', 'Jacqueline Flores'),
('CBA', 'Business Manager', 'Wade Silva'),
('CBA', 'Business Manager', 'Yvonne Jimenez'),
('CBA', 'Business Manager', 'Dale Vargas'),
('CBA', 'Business Manager', 'Wilma Ruiz'),
('CBA', 'Representative', 'Rex Romero'),
('CBA', 'Representative', 'Paulette Alvarez'),
('CBA', 'Representative', 'Terrence Perez'),
('CBA', 'Senator', 'Rosemarie Aguilar'),
('CBA', 'Senator', 'Leslie Medina'),
('CBA', 'Senator', 'Bonnie Gutierrez'),
('CBA', 'Senator', 'Preston Castillo'),
('CBA', 'Governor', 'Roberta Delgado'),
('CBA', 'Governor', 'Ramon Vega'),
('CBA', 'Governor', 'Elsie Ramirez');

-- CTHM Candidates
INSERT INTO public.candidates (department, position, candidate_name) VALUES
('CTHM', 'President', 'Kristopher Moreno'),
('CTHM', 'President', 'Monique Reyes'),
('CTHM', 'President', 'Xavier Cruz'),
('CTHM', 'Vice President', 'Yvette Torres'),
('CTHM', 'Vice President', 'Dominic Santos'),
('CTHM', 'Vice President', 'Francine Garcia'),
('CTHM', 'Secretary', 'Gilbert Ramos'),
('CTHM', 'Secretary', 'Antoinette Fernandez'),
('CTHM', 'Secretary', 'Ruben Lopez'),
('CTHM', 'Secretary', 'Colleen Gonzales'),
('CTHM', 'Treasurer', 'Marshall Diaz'),
('CTHM', 'Treasurer', 'Bernadette Martinez'),
('CTHM', 'Treasurer', 'Bradford Sanchez'),
('CTHM', 'Auditor', 'Suzanne Rivera'),
('CTHM', 'Auditor', 'Wilbur Morales'),
('CTHM', 'Auditor', 'Jacquelyn Castro'),
('CTHM', 'Auditor', 'Hubert Ortiz'),
('CTHM', 'PIO', 'Tabitha Navarro'),
('CTHM', 'PIO', 'Terrance Herrera'),
('CTHM', 'PIO', 'Rosemary Flores'),
('CTHM', 'Business Manager', 'Lester Silva'),
('CTHM', 'Business Manager', 'Henrietta Jimenez'),
('CTHM', 'Business Manager', 'Randall Vargas'),
('CTHM', 'Business Manager', 'Annette Ruiz'),
('CTHM', 'Representative', 'Kelvin Romero'),
('CTHM', 'Representative', 'Leona Alvarez'),
('CTHM', 'Representative', 'Orville Perez'),
('CTHM', 'Senator', 'Genevieve Aguilar'),
('CTHM', 'Senator', 'Irving Medina'),
('CTHM', 'Senator', 'Ramona Gutierrez'),
('CTHM', 'Senator', 'Horace Castillo'),
('CTHM', 'Governor', 'Candace Delgado'),
('CTHM', 'Governor', 'Sheldon Vega'),
('CTHM', 'Governor', 'Lorraine Ramirez');

-- College of Criminology Candidates
INSERT INTO public.candidates (department, position, candidate_name) VALUES
('College of Criminology', 'President', 'Tristan Moreno'),
('College of Criminology', 'President', 'Rochelle Reyes'),
('College of Criminology', 'President', 'Byron Cruz'),
('College of Criminology', 'Vice President', 'Sabrina Torres'),
('College of Criminology', 'Vice President', 'Fletcher Santos'),
('College of Criminology', 'Vice President', 'Bridget Garcia'),
('College of Criminology', 'Secretary', 'Lionel Ramos'),
('College of Criminology', 'Secretary', 'Rochelle Fernandez'),
('College of Criminology', 'Secretary', 'Preston Lopez'),
('College of Criminology', 'Secretary', 'Arlene Gonzales'),
('College of Criminology', 'Treasurer', 'Emilio Diaz'),
('College of Criminology', 'Treasurer', 'Belinda Martinez'),
('College of Criminology', 'Treasurer', 'Wade Sanchez'),
('College of Criminology', 'Auditor', 'Thelma Rivera'),
('College of Criminology', 'Auditor', 'Shelby Morales'),
('College of Criminology', 'Auditor', 'Olga Castro'),
('College of Criminology', 'Auditor', 'Floyd Ortiz'),
('College of Criminology', 'PIO', 'Velma Navarro'),
('College of Criminology', 'PIO', 'Lester Herrera'),
('College of Criminology', 'PIO', 'Rosalind Flores'),
('College of Criminology', 'Business Manager', 'Ruben Silva'),
('College of Criminology', 'Business Manager', 'Nora Jimenez'),
('College of Criminology', 'Business Manager', 'Tommie Vargas'),
('College of Criminology', 'Business Manager', 'Ramona Ruiz'),
('College of Criminology', 'Representative', 'Stewart Romero'),
('College of Criminology', 'Representative', 'Gwendolyn Alvarez'),
('College of Criminology', 'Representative', 'Freddie Perez'),
('College of Criminology', 'Senator', 'Alberta Aguilar'),
('College of Criminology', 'Senator', 'Jasper Medina'),
('College of Criminology', 'Senator', 'Eunice Gutierrez'),
('College of Criminology', 'Senator', 'Mitchell Castillo'),
('College of Criminology', 'Governor', 'Adrienne Delgado'),
('College of Criminology', 'Governor', 'Edmund Vega'),
('College of Criminology', 'Governor', 'Iris Ramirez');

-- College of Education Candidates
INSERT INTO public.candidates (department, position, candidate_name) VALUES
('College of Education', 'President', 'Felix Moreno'),
('College of Education', 'President', 'Meredith Reyes'),
('College of Education', 'President', 'Warren Cruz'),
('College of Education', 'Vice President', 'Muriel Torres'),
('College of Education', 'Vice President', 'Dwight Santos'),
('College of Education', 'Vice President', 'Estelle Garcia'),
('College of Education', 'Secretary', 'Homer Ramos'),
('College of Education', 'Secretary', 'Wanda Fernandez'),
('College of Education', 'Secretary', 'Lionel Lopez'),
('College of Education', 'Secretary', 'Maxine Gonzales'),
('College of Education', 'Treasurer', 'Vernon Diaz'),
('College of Education', 'Treasurer', 'Opal Martinez'),
('College of Education', 'Treasurer', 'Elmer Sanchez'),
('College of Education', 'Auditor', 'Pearl Rivera'),
('College of Education', 'Auditor', 'Clayton Morales'),
('College of Education', 'Auditor', 'Hazel Castro'),
('College of Education', 'Auditor', 'Gerard Ortiz'),
('College of Education', 'PIO', 'Ruby Navarro'),
('College of Education', 'PIO', 'Cedric Herrera'),
('College of Education', 'PIO', 'Mabel Flores'),
('College of Education', 'Business Manager', 'Archie Silva'),
('College of Education', 'Business Manager', 'Olive Jimenez'),
('College of Education', 'Business Manager', 'Rufus Vargas'),
('College of Education', 'Business Manager', 'Della Ruiz'),
('College of Education', 'Representative', 'Chester Romero'),
('College of Education', 'Representative', 'Mamie Alvarez'),
('College of Education', 'Representative', 'Irving Perez'),
('College of Education', 'Senator', 'Nellie Aguilar'),
('College of Education', 'Senator', 'Earnest Medina'),
('College of Education', 'Senator', 'Leah Gutierrez'),
('College of Education', 'Senator', 'Clifton Castillo'),
('College of Education', 'Governor', 'Bessie Delgado'),
('College of Education', 'Governor', 'Homer Vega'),
('College of Education', 'Governor', 'Blanche Ramirez');

-- College of Agriculture Candidates
INSERT INTO public.candidates (department, position, candidate_name) VALUES
('College of Agriculture', 'President', 'Luther Moreno'),
('College of Agriculture', 'President', 'Minnie Reyes'),
('College of Agriculture', 'President', 'Lyle Cruz'),
('College of Agriculture', 'Vice President', 'Mae Torres'),
('College of Agriculture', 'Vice President', 'Maurice Santos'),
('College of Agriculture', 'Vice President', 'Essie Garcia'),
('College of Agriculture', 'Secretary', 'Leland Ramos'),
('College of Agriculture', 'Secretary', 'Fannie Fernandez'),
('College of Agriculture', 'Secretary', 'Bert Lopez'),
('College of Agriculture', 'Secretary', 'Cora Gonzales'),
('College of Agriculture', 'Treasurer', 'Woodrow Diaz'),
('College of Agriculture', 'Treasurer', 'Augusta Martinez'),
('College of Agriculture', 'Treasurer', 'Silas Sanchez'),
('College of Agriculture', 'Auditor', 'Hattie Rivera'),
('College of Agriculture', 'Auditor', 'Wilfred Morales'),
('College of Agriculture', 'Auditor', 'Adeline Castro'),
('College of Agriculture', 'Auditor', 'Emery Ortiz'),
('College of Agriculture', 'PIO', 'Myrtle Navarro'),
('College of Agriculture', 'PIO', 'Roscoe Herrera'),
('College of Agriculture', 'PIO', 'Lela Flores'),
('College of Agriculture', 'Business Manager', 'Thaddeus Silva'),
('College of Agriculture', 'Business Manager', 'Matilda Jimenez'),
('College of Agriculture', 'Business Manager', 'Wilbur Vargas'),
('College of Agriculture', 'Business Manager', 'Effie Ruiz'),
('College of Agriculture', 'Representative', 'Otis Romero'),
('College of Agriculture', 'Representative', 'Edith Alvarez'),
('College of Agriculture', 'Representative', 'Clyde Perez'),
('College of Agriculture', 'Senator', 'Lela Aguilar'),
('College of Agriculture', 'Senator', 'Alonzo Medina'),
('College of Agriculture', 'Senator', 'Myrtle Gutierrez'),
('College of Agriculture', 'Senator', 'Elbert Castillo'),
('College of Agriculture', 'Governor', 'Sadie Delgado'),
('College of Agriculture', 'Governor', 'Levi Vega'),
('College of Agriculture', 'Governor', 'Florence Ramirez');

-- Insert partylists for all departments
INSERT INTO public.partylists (department, name, description) VALUES
-- CCS
('CCS', 'Tech Innovators Party', 'Focused on advancing technology and innovation in the college'),
('CCS', 'Code Alliance', 'Promoting collaboration and excellence in programming'),
('CCS', 'Cyber Unity', 'Dedicated to cybersecurity awareness and digital safety'),
('CCS', 'IT Empowerment League', 'Empowering students through technology education'),
-- BS Nursing
('BS Nursing', 'Caregivers United', 'Supporting excellence in patient care and compassion'),
('BS Nursing', 'Nightingale Partylist', 'Upholding the highest standards of nursing practice'),
('BS Nursing', 'Healing Hands Movement', 'Promoting holistic healthcare and wellness'),
('BS Nursing', 'Lifeline Alliance', 'Dedicated to saving lives and community health'),
-- Psychology
('College of Psychology', 'Mind Matters Coalition', 'Advancing mental health awareness and support'),
('College of Psychology', 'Psych Advocates', 'Championing psychological wellbeing for all'),
('College of Psychology', 'Wellness Front', 'Promoting mental and emotional wellness'),
('College of Psychology', 'Insight Party', 'Fostering deeper understanding of human behavior'),
-- Engineering
('College of Engineering', 'Builders Front', 'Building tomorrow through innovative engineering'),
('College of Engineering', 'Innovatech Party', 'Merging innovation with technical excellence'),
('College of Engineering', 'Gearheads League', 'Passionate about mechanical and technical solutions'),
('College of Engineering', 'TechBuilders Movement', 'Constructing the future through technology'),
-- CAS
('CAS', 'Liberal Voices', 'Celebrating diversity in arts and sciences'),
('CAS', 'Visionaries United', 'Envisioning a brighter future through knowledge'),
('CAS', 'Arts & Logic Party', 'Balancing creativity with analytical thinking'),
('CAS', 'Frontier Scholars', 'Pushing boundaries in arts and sciences'),
-- CBA
('CBA', 'Entrepreneurial Alliance', 'Fostering business innovation and entrepreneurship'),
('CBA', 'Market Leaders Party', 'Leading the way in business excellence'),
('CBA', 'Success Vision', 'Achieving success through strategic planning'),
('CBA', 'Future Executives Coalition', 'Preparing tomorrow business leaders today'),
-- CTHM
('CTHM', 'Travel Front Party', 'Advancing tourism and travel industry standards'),
('CTHM', 'Culinary Pioneers', 'Innovating in hospitality and culinary arts'),
('CTHM', 'Global Hosts Movement', 'Promoting world-class hospitality service'),
('CTHM', 'Service Excellence Coalition', 'Delivering exceptional customer experiences'),
-- Criminology
('College of Criminology', 'Justice Front Party', 'Upholding justice and the rule of law'),
('College of Criminology', 'Peacekeepers Alliance', 'Maintaining peace and order in communities'),
('College of Criminology', 'Law Enforcers United', 'United in enforcing the law fairly'),
('College of Criminology', 'Order and Integrity Movement', 'Promoting integrity in law enforcement'),
-- Education
('College of Education', 'EduLeaders Party', 'Leading educational transformation and innovation'),
('College of Education', 'Future Mentors Coalition', 'Shaping future generations of educators'),
('College of Education', 'Learning First Movement', 'Prioritizing quality education for all'),
('College of Education', 'Academic Builders Party', 'Building strong academic foundations'),
-- Agriculture
('College of Agriculture', 'GreenGrowers Party', 'Promoting sustainable agriculture practices'),
('College of Agriculture', 'AgriTech Alliance', 'Integrating technology in modern farming'),
('College of Agriculture', 'Sustainable Farmers League', 'Committed to environmental sustainability'),
('College of Agriculture', 'Harvest Front Movement', 'Ensuring food security and agricultural prosperity');